package com.project.dms.dao;

import com.project.dms.entiy.DrugConditionDef;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface DrugConditionDefMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drug_condition_def
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer conditionIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drug_condition_def
	 * @mbggenerated
	 */
	int insert(DrugConditionDef record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drug_condition_def
	 * @mbggenerated
	 */
	DrugConditionDef selectByPrimaryKey(Integer conditionIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drug_condition_def
	 * @mbggenerated
	 */
	List<DrugConditionDef> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table drug_condition_def
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DrugConditionDef record);
}