package com.project.dms.dao;

import com.project.dms.entiy.DrugConditionList;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface DrugConditionListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_condition_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer drugSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_condition_list
     *
     * @mbggenerated
     */
    int insert(DrugConditionList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_condition_list
     *
     * @mbggenerated
     */
    DrugConditionList selectByPrimaryKey(Integer drugSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_condition_list
     *
     * @mbggenerated
     */
    List<DrugConditionList> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_condition_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DrugConditionList record);
}