package com.project.dms.dao;

import com.project.dms.entiy.DrugDefinedMain;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DrugDefinedMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_defined_main
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer drugSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_defined_main
     *
     * @mbggenerated
     */
    int insert(DrugDefinedMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_defined_main
     *
     * @mbggenerated
     */
    DrugDefinedMain selectByPrimaryKey(Integer drugSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_defined_main
     *
     * @mbggenerated
     */
    List<DrugDefinedMain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_defined_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DrugDefinedMain record);
    
    List<DrugDefinedMain> selectByModel(DrugDefinedMain record);
    
    List<Map<String,Object>> selectYaofangByParts(@Param("symptomsSeq")int symptomsSeq,@Param("organsSeq")int organsSeq,@Param("tongueSeq")int tongueSeq,@Param("seasonSeq")int seasonSeq,@Param("yearType")int yearType,@Param("timeType")int timeType,@Param("parts")String parts);
    
    List<Map<String,Object>> selectYaofangByParts2(@Param("symptomsSeq")int symptomsSeq,@Param("organsSeq")int organsSeq,@Param("tongueSeq")int tongueSeq,@Param("seasonSeq")int seasonSeq,@Param("yearType")int yearType,@Param("timeType")int timeType,@Param("parts")String parts);
}