package com.project.dms.dao;

import com.project.dms.entiy.InquiryRcdSub;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface InquiryRcdSubMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_sub
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer conditionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_sub
	 * @mbggenerated
	 */
	int insert(InquiryRcdSub record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_sub
	 * @mbggenerated
	 */
	InquiryRcdSub selectByPrimaryKey(Integer conditionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_sub
	 * @mbggenerated
	 */
	List<InquiryRcdSub> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_sub
	 * @mbggenerated
	 */
	int updateByPrimaryKey(InquiryRcdSub record);
	
	List<InquiryRcdSub> selectInquiryRcdSubByMainidAndSymptomsSeq(@Param("inquiryId") Integer inquiryId,@Param("symptomsSeq")Integer symptomsSeq);
	
	List<InquiryRcdSub> selectByInquiryId(Integer inquiryId);
	
	
}