package com.project.dms.dao;

import com.project.dms.entiy.InquiryRcdCondition;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface InquiryRcdConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_rcd_condition
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer conditionSubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_rcd_condition
     *
     * @mbggenerated
     */
    int insert(InquiryRcdCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_rcd_condition
     *
     * @mbggenerated
     */
    InquiryRcdCondition selectByPrimaryKey(Integer conditionSubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_rcd_condition
     *
     * @mbggenerated
     */
    List<InquiryRcdCondition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_rcd_condition
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InquiryRcdCondition record);
}