package com.project.dms.dao;

import com.project.dms.entiy.InquiryRcdMain;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface InquiryRcdMainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_main
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer inquiryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_main
	 * @mbggenerated
	 */
	int insert(InquiryRcdMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_main
	 * @mbggenerated
	 */
	InquiryRcdMain selectByPrimaryKey(Integer inquiryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_main
	 * @mbggenerated
	 */
	List<InquiryRcdMain> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_main
	 * @mbggenerated
	 */
	int updateByPrimaryKey(InquiryRcdMain record);
	
	List<InquiryRcdMain> selectByKey(@Param("key") String key);
}