package com.project.dms.dao;

import com.project.dms.entiy.PerSysList;
import com.project.dms.entiy.PerSysSub;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PerSysSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table per_sys_sub
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer perSeqx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table per_sys_sub
     *
     * @mbggenerated
     */
    int insert(PerSysSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table per_sys_sub
     *
     * @mbggenerated
     */
    PerSysSub selectByPrimaryKey(Integer perSeqx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table per_sys_sub
     *
     * @mbggenerated
     */
    List<PerSysSub> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table per_sys_sub
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PerSysSub record);
    
    List<PerSysSub> selectByPerid(String perId);
    
    List<PerSysSub> selectByPeridOrPhone(@Param("key")String key);
    
    List<PerSysSub> selectByKey(@Param("key")String key);
}