package com.project.dms.dao;

import com.project.dms.entiy.PerSysList;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface PerSysListMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table per_sys_list
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer perSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table per_sys_list
	 * @mbggenerated
	 */
	int insert(PerSysList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table per_sys_list
	 * @mbggenerated
	 */
	PerSysList selectByPrimaryKey(Integer perSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table per_sys_list
	 * @mbggenerated
	 */
	List<PerSysList> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table per_sys_list
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PerSysList record);

	List<PerSysList> selectByPerid(String perId);
}