package com.project.dms.dao;

import com.project.dms.entiy.PhyConditionDrug;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface PhyConditionDrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_condition_drug
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer drugSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_condition_drug
     *
     * @mbggenerated
     */
    int insert(PhyConditionDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_condition_drug
     *
     * @mbggenerated
     */
    PhyConditionDrug selectByPrimaryKey(Integer drugSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_condition_drug
     *
     * @mbggenerated
     */
    List<PhyConditionDrug> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_condition_drug
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhyConditionDrug record);
}