package com.project.dms.dao;

import com.project.dms.entiy.PhyConditionType;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface PhyConditionTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_condition_type
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer conditionIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_condition_type
	 * @mbggenerated
	 */
	int insert(PhyConditionType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_condition_type
	 * @mbggenerated
	 */
	PhyConditionType selectByPrimaryKey(Integer conditionIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_condition_type
	 * @mbggenerated
	 */
	List<PhyConditionType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_condition_type
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PhyConditionType record);
	
	List<PhyConditionType> selectRecordByInquiryId(Integer inquiryId);
	
	List<Map<String,Object>> selectRecordDetailByConditionIdx(int conditionIdx);
	
	List<Map<String,Object>> selectDrugDetailByConditionIdx(int conditionIdx);
}