package com.project.dms.dao;

import com.project.dms.entiy.PhyOrgansType;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface PhyOrgansTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_organs_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer organsSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_organs_type
     *
     * @mbggenerated
     */
    int insert(PhyOrgansType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_organs_type
     *
     * @mbggenerated
     */
    PhyOrgansType selectByPrimaryKey(Integer organsSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_organs_type
     *
     * @mbggenerated
     */
    List<PhyOrgansType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_organs_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhyOrgansType record);
}