package com.project.dms.dao;

import com.project.dms.entiy.PhyPartType;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface PhyPartTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_part_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer phySeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_part_type
     *
     * @mbggenerated
     */
    int insert(PhyPartType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_part_type
     *
     * @mbggenerated
     */
    PhyPartType selectByPrimaryKey(Integer phySeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_part_type
     *
     * @mbggenerated
     */
    List<PhyPartType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_part_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhyPartType record);
    
    List<PhyPartType> selectByPhyseqs(String phySeqs);
}