package com.project.dms.dao;

import com.project.dms.entiy.PhySymptomsType;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PhySymptomsTypeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_symptoms_type
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer symptomsSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_symptoms_type
	 * @mbggenerated
	 */
	int insert(PhySymptomsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_symptoms_type
	 * @mbggenerated
	 */
	PhySymptomsType selectByPrimaryKey(Integer symptomsSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_symptoms_type
	 * @mbggenerated
	 */
	List<PhySymptomsType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_symptoms_type
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PhySymptomsType record);

	List<Map<String,Object>> selectByKeyWord(@Param("keyWord") String keyWord);
	List<Map<String,Object>> selectByIds(@Param("ids") String ids);
	
}