package com.project.dms.entiy;

import java.io.Serializable;
import java.math.BigDecimal;

public class DrugListDef implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_list_def.DRUG_ID
     *
     * @mbggenerated
     */
    private Integer drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_list_def.DRUG_CODE
     *
     * @mbggenerated
     */
    private String drugCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_list_def.DRUG_TYPE
     *
     * @mbggenerated
     */
    private String drugType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_list_def.DRUG_NAME
     *
     * @mbggenerated
     */
    private String drugName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_list_def.UNIT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_list_def
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_list_def.DRUG_ID
     *
     * @return the value of drug_list_def.DRUG_ID
     *
     * @mbggenerated
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_list_def.DRUG_ID
     *
     * @param drugId the value for drug_list_def.DRUG_ID
     *
     * @mbggenerated
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_list_def.DRUG_CODE
     *
     * @return the value of drug_list_def.DRUG_CODE
     *
     * @mbggenerated
     */
    public String getDrugCode() {
        return drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_list_def.DRUG_CODE
     *
     * @param drugCode the value for drug_list_def.DRUG_CODE
     *
     * @mbggenerated
     */
    public void setDrugCode(String drugCode) {
        this.drugCode = drugCode == null ? null : drugCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_list_def.DRUG_TYPE
     *
     * @return the value of drug_list_def.DRUG_TYPE
     *
     * @mbggenerated
     */
    public String getDrugType() {
        return drugType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_list_def.DRUG_TYPE
     *
     * @param drugType the value for drug_list_def.DRUG_TYPE
     *
     * @mbggenerated
     */
    public void setDrugType(String drugType) {
        this.drugType = drugType == null ? null : drugType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_list_def.DRUG_NAME
     *
     * @return the value of drug_list_def.DRUG_NAME
     *
     * @mbggenerated
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_list_def.DRUG_NAME
     *
     * @param drugName the value for drug_list_def.DRUG_NAME
     *
     * @mbggenerated
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_list_def.UNIT_PRICE
     *
     * @return the value of drug_list_def.UNIT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_list_def.UNIT_PRICE
     *
     * @param unitPrice the value for drug_list_def.UNIT_PRICE
     *
     * @mbggenerated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_list_def
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", drugId=").append(drugId);
        sb.append(", drugCode=").append(drugCode);
        sb.append(", drugType=").append(drugType);
        sb.append(", drugName=").append(drugName);
        sb.append(", unitPrice=").append(unitPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}