package com.project.dms.entiy;

import java.io.Serializable;
import java.util.Date;

public class DrugDefinedMain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.DRUG_SEQ_ID
     *
     * @mbggenerated
     */
    private Integer drugSeqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.SYMPTOMS_SEQ
     *
     * @mbggenerated
     */
    private Integer symptomsSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.ORGANS_SEQ
     *
     * @mbggenerated
     */
    private Integer organsSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.TONGUE_SEQ
     *
     * @mbggenerated
     */
    private Integer tongueSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.SEASON_SEQ
     *
     * @mbggenerated
     */
    private Integer seasonSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.YEAR_SEQ
     *
     * @mbggenerated
     */
    private Integer yearSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.TIME_SEQ
     *
     * @mbggenerated
     */
    private Integer timeSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.PHY_SEQ
     *
     * @mbggenerated
     */
    private Integer phySeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_defined_main.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_defined_main
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.DRUG_SEQ_ID
     *
     * @return the value of drug_defined_main.DRUG_SEQ_ID
     *
     * @mbggenerated
     */
    public Integer getDrugSeqId() {
        return drugSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.DRUG_SEQ_ID
     *
     * @param drugSeqId the value for drug_defined_main.DRUG_SEQ_ID
     *
     * @mbggenerated
     */
    public void setDrugSeqId(Integer drugSeqId) {
        this.drugSeqId = drugSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.SYMPTOMS_SEQ
     *
     * @return the value of drug_defined_main.SYMPTOMS_SEQ
     *
     * @mbggenerated
     */
    public Integer getSymptomsSeq() {
        return symptomsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.SYMPTOMS_SEQ
     *
     * @param symptomsSeq the value for drug_defined_main.SYMPTOMS_SEQ
     *
     * @mbggenerated
     */
    public void setSymptomsSeq(Integer symptomsSeq) {
        this.symptomsSeq = symptomsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.ORGANS_SEQ
     *
     * @return the value of drug_defined_main.ORGANS_SEQ
     *
     * @mbggenerated
     */
    public Integer getOrgansSeq() {
        return organsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.ORGANS_SEQ
     *
     * @param organsSeq the value for drug_defined_main.ORGANS_SEQ
     *
     * @mbggenerated
     */
    public void setOrgansSeq(Integer organsSeq) {
        this.organsSeq = organsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.TONGUE_SEQ
     *
     * @return the value of drug_defined_main.TONGUE_SEQ
     *
     * @mbggenerated
     */
    public Integer getTongueSeq() {
        return tongueSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.TONGUE_SEQ
     *
     * @param tongueSeq the value for drug_defined_main.TONGUE_SEQ
     *
     * @mbggenerated
     */
    public void setTongueSeq(Integer tongueSeq) {
        this.tongueSeq = tongueSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.SEASON_SEQ
     *
     * @return the value of drug_defined_main.SEASON_SEQ
     *
     * @mbggenerated
     */
    public Integer getSeasonSeq() {
        return seasonSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.SEASON_SEQ
     *
     * @param seasonSeq the value for drug_defined_main.SEASON_SEQ
     *
     * @mbggenerated
     */
    public void setSeasonSeq(Integer seasonSeq) {
        this.seasonSeq = seasonSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.YEAR_SEQ
     *
     * @return the value of drug_defined_main.YEAR_SEQ
     *
     * @mbggenerated
     */
    public Integer getYearSeq() {
        return yearSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.YEAR_SEQ
     *
     * @param yearSeq the value for drug_defined_main.YEAR_SEQ
     *
     * @mbggenerated
     */
    public void setYearSeq(Integer yearSeq) {
        this.yearSeq = yearSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.TIME_SEQ
     *
     * @return the value of drug_defined_main.TIME_SEQ
     *
     * @mbggenerated
     */
    public Integer getTimeSeq() {
        return timeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.TIME_SEQ
     *
     * @param timeSeq the value for drug_defined_main.TIME_SEQ
     *
     * @mbggenerated
     */
    public void setTimeSeq(Integer timeSeq) {
        this.timeSeq = timeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.PHY_SEQ
     *
     * @return the value of drug_defined_main.PHY_SEQ
     *
     * @mbggenerated
     */
    public Integer getPhySeq() {
        return phySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.PHY_SEQ
     *
     * @param phySeq the value for drug_defined_main.PHY_SEQ
     *
     * @mbggenerated
     */
    public void setPhySeq(Integer phySeq) {
        this.phySeq = phySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_defined_main.CREATE_TIME
     *
     * @return the value of drug_defined_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_defined_main.CREATE_TIME
     *
     * @param createTime the value for drug_defined_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_defined_main
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", drugSeqId=").append(drugSeqId);
        sb.append(", symptomsSeq=").append(symptomsSeq);
        sb.append(", organsSeq=").append(organsSeq);
        sb.append(", tongueSeq=").append(tongueSeq);
        sb.append(", seasonSeq=").append(seasonSeq);
        sb.append(", yearSeq=").append(yearSeq);
        sb.append(", timeSeq=").append(timeSeq);
        sb.append(", phySeq=").append(phySeq);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}