package com.project.dms.entiy;

import java.io.Serializable;

public class InquiryRcdMain implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.INQUIRY_ID
	 * @mbggenerated
	 */
	private Integer inquiryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.PER_NAME
	 * @mbggenerated
	 */
	private String perName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.PER_ID
	 * @mbggenerated
	 */
	private String perId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.INQUIRY_TIME
	 * @mbggenerated
	 */
	private String inquiryTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.PER_NAME_IN
	 * @mbggenerated
	 */
	private String perNameIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.INQUIRY_CONTENT
	 * @mbggenerated
	 */
	private String inquiryContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.RECORD_CLOSE
	 * @mbggenerated
	 */
	private String recordClose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_main.USE_FLAG
	 * @mbggenerated
	 */
	private String useFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table inquiry_rcd_main
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.INQUIRY_ID
	 * @return  the value of inquiry_rcd_main.INQUIRY_ID
	 * @mbggenerated
	 */
	public Integer getInquiryId() {
		return inquiryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.INQUIRY_ID
	 * @param inquiryId  the value for inquiry_rcd_main.INQUIRY_ID
	 * @mbggenerated
	 */
	public void setInquiryId(Integer inquiryId) {
		this.inquiryId = inquiryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.PER_NAME
	 * @return  the value of inquiry_rcd_main.PER_NAME
	 * @mbggenerated
	 */
	public String getPerName() {
		return perName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.PER_NAME
	 * @param perName  the value for inquiry_rcd_main.PER_NAME
	 * @mbggenerated
	 */
	public void setPerName(String perName) {
		this.perName = perName == null ? null : perName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.PER_ID
	 * @return  the value of inquiry_rcd_main.PER_ID
	 * @mbggenerated
	 */
	public String getPerId() {
		return perId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.PER_ID
	 * @param perId  the value for inquiry_rcd_main.PER_ID
	 * @mbggenerated
	 */
	public void setPerId(String perId) {
		this.perId = perId == null ? null : perId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.INQUIRY_TIME
	 * @return  the value of inquiry_rcd_main.INQUIRY_TIME
	 * @mbggenerated
	 */
	public String getInquiryTime() {
		return inquiryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.INQUIRY_TIME
	 * @param inquiryTime  the value for inquiry_rcd_main.INQUIRY_TIME
	 * @mbggenerated
	 */
	public void setInquiryTime(String inquiryTime) {
		this.inquiryTime = inquiryTime == null ? null : inquiryTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.PER_NAME_IN
	 * @return  the value of inquiry_rcd_main.PER_NAME_IN
	 * @mbggenerated
	 */
	public String getPerNameIn() {
		return perNameIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.PER_NAME_IN
	 * @param perNameIn  the value for inquiry_rcd_main.PER_NAME_IN
	 * @mbggenerated
	 */
	public void setPerNameIn(String perNameIn) {
		this.perNameIn = perNameIn == null ? null : perNameIn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.INQUIRY_CONTENT
	 * @return  the value of inquiry_rcd_main.INQUIRY_CONTENT
	 * @mbggenerated
	 */
	public String getInquiryContent() {
		return inquiryContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.INQUIRY_CONTENT
	 * @param inquiryContent  the value for inquiry_rcd_main.INQUIRY_CONTENT
	 * @mbggenerated
	 */
	public void setInquiryContent(String inquiryContent) {
		this.inquiryContent = inquiryContent == null ? null : inquiryContent
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.RECORD_CLOSE
	 * @return  the value of inquiry_rcd_main.RECORD_CLOSE
	 * @mbggenerated
	 */
	public String getRecordClose() {
		return recordClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.RECORD_CLOSE
	 * @param recordClose  the value for inquiry_rcd_main.RECORD_CLOSE
	 * @mbggenerated
	 */
	public void setRecordClose(String recordClose) {
		this.recordClose = recordClose == null ? null : recordClose.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_main.USE_FLAG
	 * @return  the value of inquiry_rcd_main.USE_FLAG
	 * @mbggenerated
	 */
	public String getUseFlag() {
		return useFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_main.USE_FLAG
	 * @param useFlag  the value for inquiry_rcd_main.USE_FLAG
	 * @mbggenerated
	 */
	public void setUseFlag(String useFlag) {
		this.useFlag = useFlag == null ? null : useFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_main
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", inquiryId=").append(inquiryId);
		sb.append(", perName=").append(perName);
		sb.append(", perId=").append(perId);
		sb.append(", inquiryTime=").append(inquiryTime);
		sb.append(", perNameIn=").append(perNameIn);
		sb.append(", inquiryContent=").append(inquiryContent);
		sb.append(", recordClose=").append(recordClose);
		sb.append(", useFlag=").append(useFlag);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}