package com.project.dms.entiy;

import java.io.Serializable;
import java.util.Date;

public class InquiryRcdSub implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.CONDITION_ID
	 * @mbggenerated
	 */
	private Integer conditionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.INQUIRY_ID
	 * @mbggenerated
	 */
	private Integer inquiryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	private Integer symptomsSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.SYMPTOMS_PRI
	 * @mbggenerated
	 */
	private Integer symptomsPri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.SYMPTOMS_NAME
	 * @mbggenerated
	 */
	private String symptomsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.SYMPTOMS_TYPE
	 * @mbggenerated
	 */
	private String symptomsType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.PHY_BELONG
	 * @mbggenerated
	 */
	private Integer phyBelong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.CONDITION_IF
	 * @mbggenerated
	 */
	private String conditionIf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.CONDITION_TIME
	 * @mbggenerated
	 */
	private Date conditionTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.RECORD_CLOSE
	 * @mbggenerated
	 */
	private String recordClose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.ORGANS_SEQ
	 * @mbggenerated
	 */
	private Integer organsSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.TONGUE_SEQ
	 * @mbggenerated
	 */
	private Integer tongueSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.TONGUE_PIC_ID1
	 * @mbggenerated
	 */
	private String tonguePicId1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.TONGUE_PIC_ID2
	 * @mbggenerated
	 */
	private String tonguePicId2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.TONGUE_PIC_ID3
	 * @mbggenerated
	 */
	private String tonguePicId3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.TONGUE_PIC_ID4
	 * @mbggenerated
	 */
	private String tonguePicId4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_rcd_sub.TONGUE_PIC_ID5
	 * @mbggenerated
	 */
	private String tonguePicId5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table inquiry_rcd_sub
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.CONDITION_ID
	 * @return  the value of inquiry_rcd_sub.CONDITION_ID
	 * @mbggenerated
	 */
	public Integer getConditionId() {
		return conditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.CONDITION_ID
	 * @param conditionId  the value for inquiry_rcd_sub.CONDITION_ID
	 * @mbggenerated
	 */
	public void setConditionId(Integer conditionId) {
		this.conditionId = conditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.INQUIRY_ID
	 * @return  the value of inquiry_rcd_sub.INQUIRY_ID
	 * @mbggenerated
	 */
	public Integer getInquiryId() {
		return inquiryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.INQUIRY_ID
	 * @param inquiryId  the value for inquiry_rcd_sub.INQUIRY_ID
	 * @mbggenerated
	 */
	public void setInquiryId(Integer inquiryId) {
		this.inquiryId = inquiryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.SYMPTOMS_SEQ
	 * @return  the value of inquiry_rcd_sub.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	public Integer getSymptomsSeq() {
		return symptomsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.SYMPTOMS_SEQ
	 * @param symptomsSeq  the value for inquiry_rcd_sub.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	public void setSymptomsSeq(Integer symptomsSeq) {
		this.symptomsSeq = symptomsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.SYMPTOMS_PRI
	 * @return  the value of inquiry_rcd_sub.SYMPTOMS_PRI
	 * @mbggenerated
	 */
	public Integer getSymptomsPri() {
		return symptomsPri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.SYMPTOMS_PRI
	 * @param symptomsPri  the value for inquiry_rcd_sub.SYMPTOMS_PRI
	 * @mbggenerated
	 */
	public void setSymptomsPri(Integer symptomsPri) {
		this.symptomsPri = symptomsPri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.SYMPTOMS_NAME
	 * @return  the value of inquiry_rcd_sub.SYMPTOMS_NAME
	 * @mbggenerated
	 */
	public String getSymptomsName() {
		return symptomsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.SYMPTOMS_NAME
	 * @param symptomsName  the value for inquiry_rcd_sub.SYMPTOMS_NAME
	 * @mbggenerated
	 */
	public void setSymptomsName(String symptomsName) {
		this.symptomsName = symptomsName == null ? null : symptomsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.SYMPTOMS_TYPE
	 * @return  the value of inquiry_rcd_sub.SYMPTOMS_TYPE
	 * @mbggenerated
	 */
	public String getSymptomsType() {
		return symptomsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.SYMPTOMS_TYPE
	 * @param symptomsType  the value for inquiry_rcd_sub.SYMPTOMS_TYPE
	 * @mbggenerated
	 */
	public void setSymptomsType(String symptomsType) {
		this.symptomsType = symptomsType == null ? null : symptomsType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.PHY_BELONG
	 * @return  the value of inquiry_rcd_sub.PHY_BELONG
	 * @mbggenerated
	 */
	public Integer getPhyBelong() {
		return phyBelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.PHY_BELONG
	 * @param phyBelong  the value for inquiry_rcd_sub.PHY_BELONG
	 * @mbggenerated
	 */
	public void setPhyBelong(Integer phyBelong) {
		this.phyBelong = phyBelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.CONDITION_IF
	 * @return  the value of inquiry_rcd_sub.CONDITION_IF
	 * @mbggenerated
	 */
	public String getConditionIf() {
		return conditionIf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.CONDITION_IF
	 * @param conditionIf  the value for inquiry_rcd_sub.CONDITION_IF
	 * @mbggenerated
	 */
	public void setConditionIf(String conditionIf) {
		this.conditionIf = conditionIf == null ? null : conditionIf.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.CONDITION_TIME
	 * @return  the value of inquiry_rcd_sub.CONDITION_TIME
	 * @mbggenerated
	 */
	public Date getConditionTime() {
		return conditionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.CONDITION_TIME
	 * @param conditionTime  the value for inquiry_rcd_sub.CONDITION_TIME
	 * @mbggenerated
	 */
	public void setConditionTime(Date conditionTime) {
		this.conditionTime = conditionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.RECORD_CLOSE
	 * @return  the value of inquiry_rcd_sub.RECORD_CLOSE
	 * @mbggenerated
	 */
	public String getRecordClose() {
		return recordClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.RECORD_CLOSE
	 * @param recordClose  the value for inquiry_rcd_sub.RECORD_CLOSE
	 * @mbggenerated
	 */
	public void setRecordClose(String recordClose) {
		this.recordClose = recordClose == null ? null : recordClose.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.ORGANS_SEQ
	 * @return  the value of inquiry_rcd_sub.ORGANS_SEQ
	 * @mbggenerated
	 */
	public Integer getOrgansSeq() {
		return organsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.ORGANS_SEQ
	 * @param organsSeq  the value for inquiry_rcd_sub.ORGANS_SEQ
	 * @mbggenerated
	 */
	public void setOrgansSeq(Integer organsSeq) {
		this.organsSeq = organsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.TONGUE_SEQ
	 * @return  the value of inquiry_rcd_sub.TONGUE_SEQ
	 * @mbggenerated
	 */
	public Integer getTongueSeq() {
		return tongueSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.TONGUE_SEQ
	 * @param tongueSeq  the value for inquiry_rcd_sub.TONGUE_SEQ
	 * @mbggenerated
	 */
	public void setTongueSeq(Integer tongueSeq) {
		this.tongueSeq = tongueSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID1
	 * @return  the value of inquiry_rcd_sub.TONGUE_PIC_ID1
	 * @mbggenerated
	 */
	public String getTonguePicId1() {
		return tonguePicId1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID1
	 * @param tonguePicId1  the value for inquiry_rcd_sub.TONGUE_PIC_ID1
	 * @mbggenerated
	 */
	public void setTonguePicId1(String tonguePicId1) {
		this.tonguePicId1 = tonguePicId1 == null ? null : tonguePicId1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID2
	 * @return  the value of inquiry_rcd_sub.TONGUE_PIC_ID2
	 * @mbggenerated
	 */
	public String getTonguePicId2() {
		return tonguePicId2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID2
	 * @param tonguePicId2  the value for inquiry_rcd_sub.TONGUE_PIC_ID2
	 * @mbggenerated
	 */
	public void setTonguePicId2(String tonguePicId2) {
		this.tonguePicId2 = tonguePicId2 == null ? null : tonguePicId2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID3
	 * @return  the value of inquiry_rcd_sub.TONGUE_PIC_ID3
	 * @mbggenerated
	 */
	public String getTonguePicId3() {
		return tonguePicId3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID3
	 * @param tonguePicId3  the value for inquiry_rcd_sub.TONGUE_PIC_ID3
	 * @mbggenerated
	 */
	public void setTonguePicId3(String tonguePicId3) {
		this.tonguePicId3 = tonguePicId3 == null ? null : tonguePicId3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID4
	 * @return  the value of inquiry_rcd_sub.TONGUE_PIC_ID4
	 * @mbggenerated
	 */
	public String getTonguePicId4() {
		return tonguePicId4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID4
	 * @param tonguePicId4  the value for inquiry_rcd_sub.TONGUE_PIC_ID4
	 * @mbggenerated
	 */
	public void setTonguePicId4(String tonguePicId4) {
		this.tonguePicId4 = tonguePicId4 == null ? null : tonguePicId4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID5
	 * @return  the value of inquiry_rcd_sub.TONGUE_PIC_ID5
	 * @mbggenerated
	 */
	public String getTonguePicId5() {
		return tonguePicId5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_rcd_sub.TONGUE_PIC_ID5
	 * @param tonguePicId5  the value for inquiry_rcd_sub.TONGUE_PIC_ID5
	 * @mbggenerated
	 */
	public void setTonguePicId5(String tonguePicId5) {
		this.tonguePicId5 = tonguePicId5 == null ? null : tonguePicId5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_rcd_sub
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", conditionId=").append(conditionId);
		sb.append(", inquiryId=").append(inquiryId);
		sb.append(", symptomsSeq=").append(symptomsSeq);
		sb.append(", symptomsPri=").append(symptomsPri);
		sb.append(", symptomsName=").append(symptomsName);
		sb.append(", symptomsType=").append(symptomsType);
		sb.append(", phyBelong=").append(phyBelong);
		sb.append(", conditionIf=").append(conditionIf);
		sb.append(", conditionTime=").append(conditionTime);
		sb.append(", recordClose=").append(recordClose);
		sb.append(", organsSeq=").append(organsSeq);
		sb.append(", tongueSeq=").append(tongueSeq);
		sb.append(", tonguePicId1=").append(tonguePicId1);
		sb.append(", tonguePicId2=").append(tonguePicId2);
		sb.append(", tonguePicId3=").append(tonguePicId3);
		sb.append(", tonguePicId4=").append(tonguePicId4);
		sb.append(", tonguePicId5=").append(tonguePicId5);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}