package com.project.dms.entiy;

import java.io.Serializable;
import java.util.Date;

public class PerSysSub implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_SEQX
     *
     * @mbggenerated
     */
    private Integer perSeqx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_SEQ
     *
     * @mbggenerated
     */
    private Integer perSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_ID
     *
     * @mbggenerated
     */
    private String perId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_NAME
     *
     * @mbggenerated
     */
    private String perName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_SEX
     *
     * @mbggenerated
     */
    private String perSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_AGE
     *
     * @mbggenerated
     */
    private Integer perAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_TYPE
     *
     * @mbggenerated
     */
    private String perType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_TEL_NUM
     *
     * @mbggenerated
     */
    private String perTelNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_NUM
     *
     * @mbggenerated
     */
    private String perNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.PER_ADD
     *
     * @mbggenerated
     */
    private String perAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column per_sys_sub.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table per_sys_sub
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_SEQX
     *
     * @return the value of per_sys_sub.PER_SEQX
     *
     * @mbggenerated
     */
    public Integer getPerSeqx() {
        return perSeqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_SEQX
     *
     * @param perSeqx the value for per_sys_sub.PER_SEQX
     *
     * @mbggenerated
     */
    public void setPerSeqx(Integer perSeqx) {
        this.perSeqx = perSeqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_SEQ
     *
     * @return the value of per_sys_sub.PER_SEQ
     *
     * @mbggenerated
     */
    public Integer getPerSeq() {
        return perSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_SEQ
     *
     * @param perSeq the value for per_sys_sub.PER_SEQ
     *
     * @mbggenerated
     */
    public void setPerSeq(Integer perSeq) {
        this.perSeq = perSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_ID
     *
     * @return the value of per_sys_sub.PER_ID
     *
     * @mbggenerated
     */
    public String getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_ID
     *
     * @param perId the value for per_sys_sub.PER_ID
     *
     * @mbggenerated
     */
    public void setPerId(String perId) {
        this.perId = perId == null ? null : perId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_NAME
     *
     * @return the value of per_sys_sub.PER_NAME
     *
     * @mbggenerated
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_NAME
     *
     * @param perName the value for per_sys_sub.PER_NAME
     *
     * @mbggenerated
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_SEX
     *
     * @return the value of per_sys_sub.PER_SEX
     *
     * @mbggenerated
     */
    public String getPerSex() {
        return perSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_SEX
     *
     * @param perSex the value for per_sys_sub.PER_SEX
     *
     * @mbggenerated
     */
    public void setPerSex(String perSex) {
        this.perSex = perSex == null ? null : perSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_AGE
     *
     * @return the value of per_sys_sub.PER_AGE
     *
     * @mbggenerated
     */
    public Integer getPerAge() {
        return perAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_AGE
     *
     * @param perAge the value for per_sys_sub.PER_AGE
     *
     * @mbggenerated
     */
    public void setPerAge(Integer perAge) {
        this.perAge = perAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_TYPE
     *
     * @return the value of per_sys_sub.PER_TYPE
     *
     * @mbggenerated
     */
    public String getPerType() {
        return perType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_TYPE
     *
     * @param perType the value for per_sys_sub.PER_TYPE
     *
     * @mbggenerated
     */
    public void setPerType(String perType) {
        this.perType = perType == null ? null : perType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_TEL_NUM
     *
     * @return the value of per_sys_sub.PER_TEL_NUM
     *
     * @mbggenerated
     */
    public String getPerTelNum() {
        return perTelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_TEL_NUM
     *
     * @param perTelNum the value for per_sys_sub.PER_TEL_NUM
     *
     * @mbggenerated
     */
    public void setPerTelNum(String perTelNum) {
        this.perTelNum = perTelNum == null ? null : perTelNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_NUM
     *
     * @return the value of per_sys_sub.PER_NUM
     *
     * @mbggenerated
     */
    public String getPerNum() {
        return perNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_NUM
     *
     * @param perNum the value for per_sys_sub.PER_NUM
     *
     * @mbggenerated
     */
    public void setPerNum(String perNum) {
        this.perNum = perNum == null ? null : perNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.PER_ADD
     *
     * @return the value of per_sys_sub.PER_ADD
     *
     * @mbggenerated
     */
    public String getPerAdd() {
        return perAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.PER_ADD
     *
     * @param perAdd the value for per_sys_sub.PER_ADD
     *
     * @mbggenerated
     */
    public void setPerAdd(String perAdd) {
        this.perAdd = perAdd == null ? null : perAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.CREATE_BY
     *
     * @return the value of per_sys_sub.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.CREATE_BY
     *
     * @param createBy the value for per_sys_sub.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.CREATE_TIME
     *
     * @return the value of per_sys_sub.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.CREATE_TIME
     *
     * @param createTime the value for per_sys_sub.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.UPDATE_TIME
     *
     * @return the value of per_sys_sub.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.UPDATE_TIME
     *
     * @param updateTime the value for per_sys_sub.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column per_sys_sub.DEL_FLAG
     *
     * @return the value of per_sys_sub.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column per_sys_sub.DEL_FLAG
     *
     * @param delFlag the value for per_sys_sub.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table per_sys_sub
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", perSeqx=").append(perSeqx);
        sb.append(", perSeq=").append(perSeq);
        sb.append(", perId=").append(perId);
        sb.append(", perName=").append(perName);
        sb.append(", perSex=").append(perSex);
        sb.append(", perAge=").append(perAge);
        sb.append(", perType=").append(perType);
        sb.append(", perTelNum=").append(perTelNum);
        sb.append(", perNum=").append(perNum);
        sb.append(", perAdd=").append(perAdd);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}