package com.project.dms.entiy;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

public class PhyConditionType implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.CONDITION_IDX
	 * @mbggenerated
	 */
	private Integer conditionIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.CONDITION_TYPE
	 * @mbggenerated
	 */
	private String conditionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.CONDITION_SUB_ID
	 * @mbggenerated
	 */
	private Integer conditionSubId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.CONDITION_ID
	 * @mbggenerated
	 */
	private Integer conditionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	private Integer symptomsSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.CONDITION_NAME
	 * @mbggenerated
	 */
	private String conditionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.CREATE_TIME
	 * @mbggenerated
	 */
	private Date creatTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.INQUIRY_ID
	 * @mbggenerated
	 */
	private Integer inquiryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.PER_ID
	 * @mbggenerated
	 */
	private String perId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.PER_NAME_IN
	 * @mbggenerated
	 */
	private String perNameIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.CONDITION_PRICE
	 * @mbggenerated
	 */
	private BigDecimal conditionPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_condition_type.PRINT_FLAG
	 * @mbggenerated
	 */
	private Integer printFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table phy_condition_type
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.CONDITION_IDX
	 * @return  the value of phy_condition_type.CONDITION_IDX
	 * @mbggenerated
	 */
	public Integer getConditionIdx() {
		return conditionIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.CONDITION_IDX
	 * @param conditionIdx  the value for phy_condition_type.CONDITION_IDX
	 * @mbggenerated
	 */
	public void setConditionIdx(Integer conditionIdx) {
		this.conditionIdx = conditionIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.CONDITION_TYPE
	 * @return  the value of phy_condition_type.CONDITION_TYPE
	 * @mbggenerated
	 */
	public String getConditionType() {
		return conditionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.CONDITION_TYPE
	 * @param conditionType  the value for phy_condition_type.CONDITION_TYPE
	 * @mbggenerated
	 */
	public void setConditionType(String conditionType) {
		this.conditionType = conditionType == null ? null : conditionType
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.CONDITION_SUB_ID
	 * @return  the value of phy_condition_type.CONDITION_SUB_ID
	 * @mbggenerated
	 */
	public Integer getConditionSubId() {
		return conditionSubId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.CONDITION_SUB_ID
	 * @param conditionSubId  the value for phy_condition_type.CONDITION_SUB_ID
	 * @mbggenerated
	 */
	public void setConditionSubId(Integer conditionSubId) {
		this.conditionSubId = conditionSubId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.CONDITION_ID
	 * @return  the value of phy_condition_type.CONDITION_ID
	 * @mbggenerated
	 */
	public Integer getConditionId() {
		return conditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.CONDITION_ID
	 * @param conditionId  the value for phy_condition_type.CONDITION_ID
	 * @mbggenerated
	 */
	public void setConditionId(Integer conditionId) {
		this.conditionId = conditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.SYMPTOMS_SEQ
	 * @return  the value of phy_condition_type.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	public Integer getSymptomsSeq() {
		return symptomsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.SYMPTOMS_SEQ
	 * @param symptomsSeq  the value for phy_condition_type.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	public void setSymptomsSeq(Integer symptomsSeq) {
		this.symptomsSeq = symptomsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.CONDITION_NAME
	 * @return  the value of phy_condition_type.CONDITION_NAME
	 * @mbggenerated
	 */
	public String getConditionName() {
		return conditionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.CONDITION_NAME
	 * @param conditionName  the value for phy_condition_type.CONDITION_NAME
	 * @mbggenerated
	 */
	public void setConditionName(String conditionName) {
		this.conditionName = conditionName == null ? null : conditionName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.CREATE_TIME
	 * @return  the value of phy_condition_type.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreatTime() {
		return creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.CREATE_TIME
	 * @param createTime  the value for phy_condition_type.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.INQUIRY_ID
	 * @return  the value of phy_condition_type.INQUIRY_ID
	 * @mbggenerated
	 */
	public Integer getInquiryId() {
		return inquiryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.INQUIRY_ID
	 * @param inquiryId  the value for phy_condition_type.INQUIRY_ID
	 * @mbggenerated
	 */
	public void setInquiryId(Integer inquiryId) {
		this.inquiryId = inquiryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.PER_ID
	 * @return  the value of phy_condition_type.PER_ID
	 * @mbggenerated
	 */
	public String getPerId() {
		return perId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.PER_ID
	 * @param perId  the value for phy_condition_type.PER_ID
	 * @mbggenerated
	 */
	public void setPerId(String perId) {
		this.perId = perId == null ? null : perId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.PER_NAME_IN
	 * @return  the value of phy_condition_type.PER_NAME_IN
	 * @mbggenerated
	 */
	public String getPerNameIn() {
		return perNameIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.PER_NAME_IN
	 * @param perNameIn  the value for phy_condition_type.PER_NAME_IN
	 * @mbggenerated
	 */
	public void setPerNameIn(String perNameIn) {
		this.perNameIn = perNameIn == null ? null : perNameIn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.CONDITION_PRICE
	 * @return  the value of phy_condition_type.CONDITION_PRICE
	 * @mbggenerated
	 */
	public BigDecimal getConditionPrice() {
		return conditionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.CONDITION_PRICE
	 * @param conditionPrice  the value for phy_condition_type.CONDITION_PRICE
	 * @mbggenerated
	 */
	public void setConditionPrice(BigDecimal conditionPrice) {
		this.conditionPrice = conditionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_condition_type.PRINT_FLAG
	 * @return  the value of phy_condition_type.PRINT_FLAG
	 * @mbggenerated
	 */
	public Integer getPrintFlag() {
		return printFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_condition_type.PRINT_FLAG
	 * @param printFlag  the value for phy_condition_type.PRINT_FLAG
	 * @mbggenerated
	 */
	public void setPrintFlag(Integer printFlag) {
		this.printFlag = printFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_condition_type
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", conditionIdx=").append(conditionIdx);
		sb.append(", conditionType=").append(conditionType);
		sb.append(", conditionSubId=").append(conditionSubId);
		sb.append(", conditionId=").append(conditionId);
		sb.append(", symptomsSeq=").append(symptomsSeq);
		sb.append(", conditionName=").append(conditionName);
		sb.append(", creatTime=").append(creatTime);
		sb.append(", inquiryId=").append(inquiryId);
		sb.append(", perId=").append(perId);
		sb.append(", perNameIn=").append(perNameIn);
		sb.append(", conditionPrice=").append(conditionPrice);
		sb.append(", printFlag=").append(printFlag);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}