package com.project.dms.entiy;

import java.io.Serializable;

public class PhyConditionList implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_list.CONDITION_SUB_IDX
     *
     * @mbggenerated
     */
    private Integer conditionSubIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_list.CONDITION_TYPE
     *
     * @mbggenerated
     */
    private String conditionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_list.CONDITION_PART
     *
     * @mbggenerated
     */
    private String conditionPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_list.CONDITION_IDX
     *
     * @mbggenerated
     */
    private Integer conditionIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phy_condition_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_list.CONDITION_SUB_IDX
     *
     * @return the value of phy_condition_list.CONDITION_SUB_IDX
     *
     * @mbggenerated
     */
    public Integer getConditionSubIdx() {
        return conditionSubIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_list.CONDITION_SUB_IDX
     *
     * @param conditionSubIdx the value for phy_condition_list.CONDITION_SUB_IDX
     *
     * @mbggenerated
     */
    public void setConditionSubIdx(Integer conditionSubIdx) {
        this.conditionSubIdx = conditionSubIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_list.CONDITION_TYPE
     *
     * @return the value of phy_condition_list.CONDITION_TYPE
     *
     * @mbggenerated
     */
    public String getConditionType() {
        return conditionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_list.CONDITION_TYPE
     *
     * @param conditionType the value for phy_condition_list.CONDITION_TYPE
     *
     * @mbggenerated
     */
    public void setConditionType(String conditionType) {
        this.conditionType = conditionType == null ? null : conditionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_list.CONDITION_PART
     *
     * @return the value of phy_condition_list.CONDITION_PART
     *
     * @mbggenerated
     */
    public String getConditionPart() {
        return conditionPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_list.CONDITION_PART
     *
     * @param conditionPart the value for phy_condition_list.CONDITION_PART
     *
     * @mbggenerated
     */
    public void setConditionPart(String conditionPart) {
        this.conditionPart = conditionPart == null ? null : conditionPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_list.CONDITION_IDX
     *
     * @return the value of phy_condition_list.CONDITION_IDX
     *
     * @mbggenerated
     */
    public Integer getConditionIdx() {
        return conditionIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_list.CONDITION_IDX
     *
     * @param conditionIdx the value for phy_condition_list.CONDITION_IDX
     *
     * @mbggenerated
     */
    public void setConditionIdx(Integer conditionIdx) {
        this.conditionIdx = conditionIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_condition_list
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", conditionSubIdx=").append(conditionSubIdx);
        sb.append(", conditionType=").append(conditionType);
        sb.append(", conditionPart=").append(conditionPart);
        sb.append(", conditionIdx=").append(conditionIdx);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}