package com.project.dms.entiy;

import java.io.Serializable;
import java.math.BigDecimal;

public class PhyConditionDrug implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_drug.DRUG_SEQ_ID
     *
     * @mbggenerated
     */
    private Integer drugSeqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_drug.CONDITION_TYPE
     *
     * @mbggenerated
     */
    private String conditionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_drug.CONDITION_PART
     *
     * @mbggenerated
     */
    private String conditionPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_drug.DRUG_ID
     *
     * @mbggenerated
     */
    private Integer drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_drug.DRUG_TYPE
     *
     * @mbggenerated
     */
    private String drugType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_drug.UNIT_QTY
     *
     * @mbggenerated
     */
    private BigDecimal unitQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_condition_drug.CONDITION_SUB_IDX
     *
     * @mbggenerated
     */
    private Integer conditionSubIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phy_condition_drug
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_drug.DRUG_SEQ_ID
     *
     * @return the value of phy_condition_drug.DRUG_SEQ_ID
     *
     * @mbggenerated
     */
    public Integer getDrugSeqId() {
        return drugSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_drug.DRUG_SEQ_ID
     *
     * @param drugSeqId the value for phy_condition_drug.DRUG_SEQ_ID
     *
     * @mbggenerated
     */
    public void setDrugSeqId(Integer drugSeqId) {
        this.drugSeqId = drugSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_drug.CONDITION_TYPE
     *
     * @return the value of phy_condition_drug.CONDITION_TYPE
     *
     * @mbggenerated
     */
    public String getConditionType() {
        return conditionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_drug.CONDITION_TYPE
     *
     * @param conditionType the value for phy_condition_drug.CONDITION_TYPE
     *
     * @mbggenerated
     */
    public void setConditionType(String conditionType) {
        this.conditionType = conditionType == null ? null : conditionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_drug.CONDITION_PART
     *
     * @return the value of phy_condition_drug.CONDITION_PART
     *
     * @mbggenerated
     */
    public String getConditionPart() {
        return conditionPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_drug.CONDITION_PART
     *
     * @param conditionPart the value for phy_condition_drug.CONDITION_PART
     *
     * @mbggenerated
     */
    public void setConditionPart(String conditionPart) {
        this.conditionPart = conditionPart == null ? null : conditionPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_drug.DRUG_ID
     *
     * @return the value of phy_condition_drug.DRUG_ID
     *
     * @mbggenerated
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_drug.DRUG_ID
     *
     * @param drugId the value for phy_condition_drug.DRUG_ID
     *
     * @mbggenerated
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_drug.DRUG_TYPE
     *
     * @return the value of phy_condition_drug.DRUG_TYPE
     *
     * @mbggenerated
     */
    public String getDrugType() {
        return drugType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_drug.DRUG_TYPE
     *
     * @param drugType the value for phy_condition_drug.DRUG_TYPE
     *
     * @mbggenerated
     */
    public void setDrugType(String drugType) {
        this.drugType = drugType == null ? null : drugType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_drug.UNIT_QTY
     *
     * @return the value of phy_condition_drug.UNIT_QTY
     *
     * @mbggenerated
     */
    public BigDecimal getUnitQty() {
        return unitQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_drug.UNIT_QTY
     *
     * @param unitQty the value for phy_condition_drug.UNIT_QTY
     *
     * @mbggenerated
     */
    public void setUnitQty(BigDecimal unitQty) {
        this.unitQty = unitQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_condition_drug.CONDITION_SUB_IDX
     *
     * @return the value of phy_condition_drug.CONDITION_SUB_IDX
     *
     * @mbggenerated
     */
    public Integer getConditionSubIdx() {
        return conditionSubIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_condition_drug.CONDITION_SUB_IDX
     *
     * @param conditionSubIdx the value for phy_condition_drug.CONDITION_SUB_IDX
     *
     * @mbggenerated
     */
    public void setConditionSubIdx(Integer conditionSubIdx) {
        this.conditionSubIdx = conditionSubIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_condition_drug
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", drugSeqId=").append(drugSeqId);
        sb.append(", conditionType=").append(conditionType);
        sb.append(", conditionPart=").append(conditionPart);
        sb.append(", drugId=").append(drugId);
        sb.append(", drugType=").append(drugType);
        sb.append(", unitQty=").append(unitQty);
        sb.append(", conditionSubIdx=").append(conditionSubIdx);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}