package com.project.dms.entiy;

import java.io.Serializable;

public class PhyPartType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_part_type.PHY_SEQ
     *
     * @mbggenerated
     */
    private Integer phySeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_part_type.PHY_PART
     *
     * @mbggenerated
     */
    private String phyPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phy_part_type.PHY_PRI
     *
     * @mbggenerated
     */
    private String phyPri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phy_part_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_part_type.PHY_SEQ
     *
     * @return the value of phy_part_type.PHY_SEQ
     *
     * @mbggenerated
     */
    public Integer getPhySeq() {
        return phySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_part_type.PHY_SEQ
     *
     * @param phySeq the value for phy_part_type.PHY_SEQ
     *
     * @mbggenerated
     */
    public void setPhySeq(Integer phySeq) {
        this.phySeq = phySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_part_type.PHY_PART
     *
     * @return the value of phy_part_type.PHY_PART
     *
     * @mbggenerated
     */
    public String getPhyPart() {
        return phyPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_part_type.PHY_PART
     *
     * @param phyPart the value for phy_part_type.PHY_PART
     *
     * @mbggenerated
     */
    public void setPhyPart(String phyPart) {
        this.phyPart = phyPart == null ? null : phyPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phy_part_type.PHY_PRI
     *
     * @return the value of phy_part_type.PHY_PRI
     *
     * @mbggenerated
     */
    public String getPhyPri() {
        return phyPri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phy_part_type.PHY_PRI
     *
     * @param phyPri the value for phy_part_type.PHY_PRI
     *
     * @mbggenerated
     */
    public void setPhyPri(String phyPri) {
        this.phyPri = phyPri == null ? null : phyPri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phy_part_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", phySeq=").append(phySeq);
        sb.append(", phyPart=").append(phyPart);
        sb.append(", phyPri=").append(phyPri);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}