package com.project.dms.entiy;

import java.io.Serializable;

public class PhySymptomsType implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_symptoms_type.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	private Integer symptomsSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_symptoms_type.SYMPTOMS_PRI
	 * @mbggenerated
	 */
	private Integer symptomsPri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_symptoms_type.SYMPTOMS_NAME
	 * @mbggenerated
	 */
	private String symptomsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_symptoms_type.SYMPTOMS_TYPE
	 * @mbggenerated
	 */
	private String symptomsType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_symptoms_type.PHY_BELONG
	 * @mbggenerated
	 */
	private Integer phyBelong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phy_symptoms_type.SYMPTOMS_INFO
	 * @mbggenerated
	 */
	//private String symptomsInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table phy_symptoms_type
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_symptoms_type.SYMPTOMS_SEQ
	 * @return  the value of phy_symptoms_type.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	public Integer getSymptomsSeq() {
		return symptomsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_symptoms_type.SYMPTOMS_SEQ
	 * @param symptomsSeq  the value for phy_symptoms_type.SYMPTOMS_SEQ
	 * @mbggenerated
	 */
	public void setSymptomsSeq(Integer symptomsSeq) {
		this.symptomsSeq = symptomsSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_symptoms_type.SYMPTOMS_PRI
	 * @return  the value of phy_symptoms_type.SYMPTOMS_PRI
	 * @mbggenerated
	 */
	public Integer getSymptomsPri() {
		return symptomsPri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_symptoms_type.SYMPTOMS_PRI
	 * @param symptomsPri  the value for phy_symptoms_type.SYMPTOMS_PRI
	 * @mbggenerated
	 */
	public void setSymptomsPri(Integer symptomsPri) {
		this.symptomsPri = symptomsPri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_symptoms_type.SYMPTOMS_NAME
	 * @return  the value of phy_symptoms_type.SYMPTOMS_NAME
	 * @mbggenerated
	 */
	public String getSymptomsName() {
		return symptomsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_symptoms_type.SYMPTOMS_NAME
	 * @param symptomsName  the value for phy_symptoms_type.SYMPTOMS_NAME
	 * @mbggenerated
	 */
	public void setSymptomsName(String symptomsName) {
		this.symptomsName = symptomsName == null ? null : symptomsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_symptoms_type.SYMPTOMS_TYPE
	 * @return  the value of phy_symptoms_type.SYMPTOMS_TYPE
	 * @mbggenerated
	 */
	public String getSymptomsType() {
		return symptomsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_symptoms_type.SYMPTOMS_TYPE
	 * @param symptomsType  the value for phy_symptoms_type.SYMPTOMS_TYPE
	 * @mbggenerated
	 */
	public void setSymptomsType(String symptomsType) {
		this.symptomsType = symptomsType == null ? null : symptomsType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_symptoms_type.PHY_BELONG
	 * @return  the value of phy_symptoms_type.PHY_BELONG
	 * @mbggenerated
	 */
	public Integer getPhyBelong() {
		return phyBelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_symptoms_type.PHY_BELONG
	 * @param phyBelong  the value for phy_symptoms_type.PHY_BELONG
	 * @mbggenerated
	 */
	public void setPhyBelong(Integer phyBelong) {
		this.phyBelong = phyBelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phy_symptoms_type.SYMPTOMS_INFO
	 * @return  the value of phy_symptoms_type.SYMPTOMS_INFO
	 * @mbggenerated
	 */
//	public String getSymptomsInfo() {
//		return symptomsInfo;
//	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phy_symptoms_type.SYMPTOMS_INFO
	 * @param symptomsInfo  the value for phy_symptoms_type.SYMPTOMS_INFO
	 * @mbggenerated
	 */
//	public void setSymptomsInfo(String symptomsInfo) {
//		this.symptomsInfo = symptomsInfo == null ? null : symptomsInfo.trim();
//	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phy_symptoms_type
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", symptomsSeq=").append(symptomsSeq);
		sb.append(", symptomsPri=").append(symptomsPri);
		sb.append(", symptomsName=").append(symptomsName);
		sb.append(", symptomsType=").append(symptomsType);
		sb.append(", phyBelong=").append(phyBelong);
//		sb.append(", symptomsInfo=").append(symptomsInfo);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}